package com.clinexa.identity.common;

import java.util.UUID;

import org.hibernate.Hibernate;
import org.hibernate.annotations.UuidGenerator;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

/**
 * UUIDv7 primary key generated by the application (LLD 20 §1: time-ordered, keeps B-tree indexes compact).
 * Equality is id-based and proxy-safe; a transient entity (no id yet) is only equal to itself.
 */
@MappedSuperclass
public abstract class BaseEntity {

	@Id
	@UuidGenerator(style = UuidGenerator.Style.VERSION_7)
	@Column(name = "id", nullable = false, updatable = false)
	private UUID id;

	public UUID getId() {
		return id;
	}

	@Override
	public final boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (!(o instanceof BaseEntity other) || Hibernate.getClass(this) != Hibernate.getClass(o)) {
			return false;
		}
		return id != null && id.equals(other.getId());
	}

	@Override
	public final int hashCode() {
		return Hibernate.getClass(this).hashCode();
	}

}
