package com.clinexa.care.common;

import java.util.UUID;

import org.hibernate.Hibernate;
import org.hibernate.annotations.UuidGenerator;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

/**
 * UUIDv7 primary key generated by the application (LLD 20 §1: time-ordered, so B-tree indexes stay
 * compact), on top of the audit columns of {@link AuditTrail}. Equality is id-based and proxy-safe;
 * a transient entity is only equal to itself.
 * <p>
 * Deliberately a copy of {@code identity-service}'s rather than a shared class: {@code SEC-11} draws
 * the boundary of {@code shared} at the security primitives, and a shared persistence base class
 * would be the first step towards a shared domain — the very coupling one database per service
 * exists to avoid.
 */
@MappedSuperclass
public abstract class BaseEntity extends AuditTrail {

	@Id
	@UuidGenerator(style = UuidGenerator.Style.VERSION_7)
	@Column(name = "id", nullable = false, updatable = false)
	private UUID id;

	public UUID getId() {
		return this.id;
	}

	@Override
	public final boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (!(o instanceof BaseEntity other) || Hibernate.getClass(this) != Hibernate.getClass(o)) {
			return false;
		}
		return this.id != null && this.id.equals(other.getId());
	}

	@Override
	public final int hashCode() {
		return Hibernate.getClass(this).hashCode();
	}

}
